name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'aria2 version'
        required: true
        default: '1.37.0'
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: aria2c-x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            artifact_name: aria2c-aarch64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: aria2c-aarch64-apple-darwin
          - os: macos-13
            artifact_name: aria2c-x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build aria2 for Linux
        if: runner.os == 'Linux'
        run: ./scripts/build-linux.sh ${{ github.event.inputs.version }}
        
      - name: Build aria2 for macOS
        if: runner.os == 'macOS'
        run: ./scripts/build-macos.sh ${{ github.event.inputs.version }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/aria2-${{ github.event.inputs.version }}/src/aria2c
          if-no-files-found: error
